// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/audit/repository/audit_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "ops-server/internal/domain/audit/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// CreateLog mocks base method.
func (m *MockAuditRepository) CreateLog(ctx context.Context, l *models.Log) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLog", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLog indicates an expected call of CreateLog.
func (mr *MockAuditRepositoryMockRecorder) CreateLog(ctx, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLog", reflect.TypeOf((*MockAuditRepository)(nil).CreateLog), ctx, l)
}

// CreateTrail mocks base method.
func (m *MockAuditRepository) CreateTrail(ctx context.Context, a *models.AuditTrail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrail", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTrail indicates an expected call of CreateTrail.
func (mr *MockAuditRepositoryMockRecorder) CreateTrail(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrail", reflect.TypeOf((*MockAuditRepository)(nil).CreateTrail), ctx, a)
}

// FindTrailByID mocks base method.
func (m *MockAuditRepository) FindTrailByID(ctx context.Context, id uuid.UUID) (*models.AuditTrail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTrailByID", ctx, id)
	ret0, _ := ret[0].(*models.AuditTrail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTrailByID indicates an expected call of FindTrailByID.
func (mr *MockAuditRepositoryMockRecorder) FindTrailByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTrailByID", reflect.TypeOf((*MockAuditRepository)(nil).FindTrailByID), ctx, id)
}

// ListLogs mocks base method.
func (m *MockAuditRepository) ListLogs(ctx context.Context, filter models.LogFilterInput, from, to time.Time) ([]*models.Log, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogs", ctx, filter, from, to)
	ret0, _ := ret[0].([]*models.Log)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLogs indicates an expected call of ListLogs.
func (mr *MockAuditRepositoryMockRecorder) ListLogs(ctx, filter, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogs", reflect.TypeOf((*MockAuditRepository)(nil).ListLogs), ctx, filter, from, to)
}

// ListTrails mocks base method.
func (m *MockAuditRepository) ListTrails(ctx context.Context, filter models.AuditFilterInput, userID *uuid.UUID, from, to time.Time) ([]*models.AuditTrail, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrails", ctx, filter, userID, from, to)
	ret0, _ := ret[0].([]*models.AuditTrail)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTrails indicates an expected call of ListTrails.
func (mr *MockAuditRepositoryMockRecorder) ListTrails(ctx, filter, userID, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrails", reflect.TypeOf((*MockAuditRepository)(nil).ListTrails), ctx, filter, userID, from, to)
}
