// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "title": "OpsServer API",
        "description": "Plateforme backend ETL event-driven — API REST documentée",
        "contact": { "name": "OpsServer Support", "email": "support@opsserver.local" },
        "license": { "name": "MIT", "url": "https://opensource.org/licenses/MIT" },
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT token au format: Bearer \u003ctoken\u003e"
        }
    },
    "paths": {
        "/audit/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Lister les logs applicatifs (admin)",
                "parameters": [
                    {
                        "enum": [
                            "debug",
                            "info",
                            "warning",
                            "error",
                            "fatal"
                        ],
                        "type": "string",
                        "description": "Niveau (debug|info|warning|error|fatal)",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Service source",
                        "name": "service",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Trace ID",
                        "name": "traceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Request ID",
                        "name": "requestId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date début (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date fin (RFC3339)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_audit_models_LogResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/audit/trails": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Lister les audit trails (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ressource (ex: user)",
                        "name": "resource",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "CREATE",
                            "UPDATE",
                            "DELETE",
                            "READ",
                            "LOGIN",
                            "LOGOUT",
                            "EXPORT"
                        ],
                        "type": "string",
                        "description": "Action",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "success",
                            "failure",
                            "denied"
                        ],
                        "type": "string",
                        "description": "Résultat",
                        "name": "outcome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "UUID utilisateur",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date début (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date fin (RFC3339)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_audit_models_AuditTrailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/audit/trails/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Détail d'un audit trail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID audit trail",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_domain_audit_models.AuditTrailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Déconnexion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Renouveler le token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ops-server_internal_domain_user_models.RefreshTokenInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_domain_user_models.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Inscription d'un nouvel utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Créer un compte",
                "parameters": [
                    {
                        "description": "Données d'inscription",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ops-server_internal_domain_user_models.CreateUserInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_domain_user_models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authentification",
                "parameters": [
                    {
                        "description": "Identifiants",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ops-server_internal_domain_user_models.SignInInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_domain_user_models.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Lister les métriques",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtre nom",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "counter",
                            "gauge",
                            "histogram"
                        ],
                        "type": "string",
                        "description": "Filtre type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "realtime",
                            "hourly",
                            "daily",
                            "weekly",
                            "monthly"
                        ],
                        "type": "string",
                        "description": "Période",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date début (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date fin (RFC3339)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_metrics_models_MetricResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/metrics/events": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Lister les événements",
                "parameters": [
                    {
                        "enum": [
                            "info",
                            "warning",
                            "critical"
                        ],
                        "type": "string",
                        "description": "Sévérité",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "auth",
                            "user",
                            "system",
                            "ingestion",
                            "api"
                        ],
                        "type": "string",
                        "description": "Catégorie",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date début (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date fin (RFC3339)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_metrics_models_EventResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/metrics/events/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Détail d'un événement",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID événement",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_domain_metrics_models.EventResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mes notifications",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite (max 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "pending",
                            "sent",
                            "failed",
                            "read"
                        ],
                        "type": "string",
                        "description": "Filtre statut",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "email",
                            "push",
                            "in_app",
                            "sms"
                        ],
                        "type": "string",
                        "description": "Filtre type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_notification_models_NotificationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications/unread-count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Nombre de non-lues",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "integer",
                                                "format": "int64"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/notifications/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Supprimer une notification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID notification",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/notifications/{id}/read": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Marquer comme lue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID notification",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Lister les utilisateurs (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite (max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_user_models_UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Mon profil",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_domain_user_models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Obtenir un utilisateur (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_domain_user_models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Supprimer un utilisateur (soft-delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Mettre à jour un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Champs à modifier",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ops-server_internal_domain_user_models.UpdateUserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ops-server_internal_domain_user_models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/roles": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Assigner un rôle (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rôle à assigner",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ops-server_internal_domain_user_models.AssignRoleInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ops-server_internal_domain_audit_models.AuditAction": {
            "description": "Type pour Swagger",
            "type": "string",
            "enum": [
                "CREATE",
                "UPDATE",
                "DELETE",
                "READ",
                "LOGIN",
                "LOGOUT",
                "EXPORT"
            ],
            "x-enum-varnames": [
                "AuditActionCreate",
                "AuditActionUpdate",
                "AuditActionDelete",
                "AuditActionRead",
                "AuditActionLogin",
                "AuditActionLogout",
                "AuditActionExport"
            ]
        },
        "ops-server_internal_domain_audit_models.AuditOutcome": {
            "type": "string",
            "enum": [
                "success",
                "failure",
                "denied"
            ],
            "x-enum-varnames": [
                "AuditOutcomeSuccess",
                "AuditOutcomeFailure",
                "AuditOutcomeDenied"
            ]
        },
        "ops-server_internal_domain_audit_models.AuditTrailResponse": {
            "description": "Représentation publique d'un audit trail",
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/ops-server_internal_domain_audit_models.AuditAction"
                },
                "auditId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "ipAddress": {
                    "type": "string"
                },
                "newValues": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "oldValues": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "outcome": {
                    "$ref": "#/definitions/ops-server_internal_domain_audit_models.AuditOutcome"
                },
                "requestId": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "resourceId": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_audit_models.LogLevel": {
            "type": "string",
            "enum": [
                "debug",
                "info",
                "warning",
                "error",
                "fatal"
            ],
            "x-enum-varnames": [
                "LogLevelDebug",
                "LogLevelInfo",
                "LogLevelWarning",
                "LogLevelError",
                "LogLevelFatal"
            ]
        },
        "ops-server_internal_domain_audit_models.LogResponse": {
            "description": "Représentation publique d'un log applicatif persisté",
            "type": "object",
            "properties": {
                "callerFile": {
                    "type": "string"
                },
                "callerLine": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "level": {
                    "$ref": "#/definitions/ops-server_internal_domain_audit_models.LogLevel"
                },
                "logId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "traceId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_metrics_models.EventCategory": {
            "type": "string",
            "enum": [
                "auth",
                "user",
                "system",
                "ingestion",
                "api"
            ],
            "x-enum-varnames": [
                "EventCategoryAuth",
                "EventCategoryUser",
                "EventCategorySystem",
                "EventCategoryIngestion",
                "EventCategoryAPI"
            ]
        },
        "ops-server_internal_domain_metrics_models.EventResponse": {
            "description": "Représentation publique d'un événement observable",
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/ops-server_internal_domain_metrics_models.EventCategory"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "eventId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "occurredAt": {
                    "type": "string"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "requestId": {
                    "type": "string"
                },
                "severity": {
                    "$ref": "#/definitions/ops-server_internal_domain_metrics_models.EventSeverity"
                },
                "source": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_metrics_models.EventSeverity": {
            "type": "string",
            "enum": [
                "info",
                "warning",
                "critical"
            ],
            "x-enum-varnames": [
                "EventSeverityInfo",
                "EventSeverityWarning",
                "EventSeverityCritical"
            ]
        },
        "ops-server_internal_domain_metrics_models.MetricPeriod": {
            "type": "string",
            "enum": [
                "realtime",
                "hourly",
                "daily",
                "weekly",
                "monthly"
            ],
            "x-enum-varnames": [
                "MetricPeriodRealtime",
                "MetricPeriodHourly",
                "MetricPeriodDaily",
                "MetricPeriodWeekly",
                "MetricPeriodMonthly"
            ]
        },
        "ops-server_internal_domain_metrics_models.MetricResponse": {
            "description": "Représentation publique d'une métrique",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "metricId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "$ref": "#/definitions/ops-server_internal_domain_metrics_models.MetricPeriod"
                },
                "recordedAt": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/ops-server_internal_domain_metrics_models.MetricType"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "ops-server_internal_domain_metrics_models.MetricType": {
            "type": "string",
            "enum": [
                "counter",
                "gauge",
                "histogram"
            ],
            "x-enum-comments": {
                "MetricTypeCounter": "valeur toujours croissante",
                "MetricTypeGauge": "valeur instantanée (peut baisser)",
                "MetricTypeHistogram": "distribution de valeurs"
            },
            "x-enum-descriptions": [
                "valeur toujours croissante",
                "valeur instantanée (peut baisser)",
                "distribution de valeurs"
            ],
            "x-enum-varnames": [
                "MetricTypeCounter",
                "MetricTypeGauge",
                "MetricTypeHistogram"
            ]
        },
        "ops-server_internal_domain_notification_models.NotificationResponse": {
            "description": "Représentation publique d'une notification",
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "notificationId": {
                    "type": "string"
                },
                "readAt": {
                    "type": "string"
                },
                "retryCount": {
                    "type": "integer"
                },
                "sentAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/ops-server_internal_domain_notification_models.NotificationStatus"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/ops-server_internal_domain_notification_models.NotificationType"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_notification_models.NotificationStatus": {
            "type": "string",
            "enum": [
                "pending",
                "sent",
                "failed",
                "read"
            ],
            "x-enum-varnames": [
                "NotificationStatusPending",
                "NotificationStatusSent",
                "NotificationStatusFailed",
                "NotificationStatusRead"
            ]
        },
        "ops-server_internal_domain_notification_models.NotificationType": {
            "type": "string",
            "enum": [
                "email",
                "push",
                "in_app",
                "sms"
            ],
            "x-enum-varnames": [
                "NotificationTypeEmail",
                "NotificationTypePush",
                "NotificationTypeInApp",
                "NotificationTypeSMS"
            ]
        },
        "ops-server_internal_domain_user_models.AssignRoleInput": {
            "type": "object",
            "required": [
                "roleId"
            ],
            "properties": {
                "roleId": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_user_models.AuthResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/ops-server_internal_domain_user_models.UserResponse"
                }
            }
        },
        "ops-server_internal_domain_user_models.CreateUserInput": {
            "description": "Données pour créer un nouvel utilisateur",
            "type": "object",
            "required": [
                "email",
                "firstName",
                "identifier",
                "lastName",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "ops-server_internal_domain_user_models.PermissionAction": {
            "type": "string",
            "enum": [
                "read",
                "write",
                "delete",
                "*"
            ],
            "x-enum-varnames": [
                "ActionRead",
                "ActionWrite",
                "ActionDelete",
                "ActionAll"
            ]
        },
        "ops-server_internal_domain_user_models.PermissionResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/ops-server_internal_domain_user_models.PermissionAction"
                },
                "permissionId": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_user_models.RefreshTokenInput": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_user_models.RoleName": {
            "type": "string",
            "enum": [
                "admin",
                "ops",
                "viewer"
            ],
            "x-enum-varnames": [
                "RoleNameAdmin",
                "RoleNameOps",
                "RoleNameViewer"
            ]
        },
        "ops-server_internal_domain_user_models.RoleResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "isSystem": {
                    "type": "boolean"
                },
                "name": {
                    "$ref": "#/definitions/ops-server_internal_domain_user_models.RoleName"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ops-server_internal_domain_user_models.PermissionResponse"
                    }
                },
                "roleId": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_user_models.SignInInput": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_user_models.UpdateUserInput": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_user_models.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ops-server_internal_domain_user_models.UserRoleResponse"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_domain_user_models.UserRoleResponse": {
            "type": "object",
            "properties": {
                "assignedAt": {
                    "type": "string"
                },
                "assignedBy": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/ops-server_internal_domain_user_models.RoleResponse"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_audit_models_AuditTrailResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ops-server_internal_domain_audit_models.AuditTrailResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_audit_models_LogResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ops-server_internal_domain_audit_models.LogResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_metrics_models_EventResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ops-server_internal_domain_metrics_models.EventResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_metrics_models_MetricResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ops-server_internal_domain_metrics_models.MetricResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_notification_models_NotificationResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ops-server_internal_domain_notification_models.NotificationResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "ops-server_internal_interfaces_http_response.PaginatedData-ops-server_internal_domain_user_models_UserResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ops-server_internal_domain_user_models.UserResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "response.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "OpsServer API",
	Description:      "Plateforme backend ETL event-driven — API REST documentée",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
