// Code generated by swaggo/swag. DO NOT EDIT.
// Ce fichier est normalement généré par `swag init`.
// Il est ici pré-généré pour permettre le démarrage sans installer swag.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "MyApp API",
        "description": "Plateforme backend ETL event-driven — API REST documentée",
        "contact": { "name": "MyApp Support", "email": "support@myapp.local" },
        "license": { "name": "MIT", "url": "https://opensource.org/licenses/MIT" },
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "schemes": ["http","https"],
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT token au format: Bearer \u003ctoken\u003e"
        }
    },
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "MyApp API",
	Description:      "Plateforme backend ETL event-driven — API REST documentée",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
