// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/metrics/repository/metrics_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "ops-server/internal/domain/metrics/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMetricsRepository is a mock of MetricsRepository interface.
type MockMetricsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRepositoryMockRecorder
}

// MockMetricsRepositoryMockRecorder is the mock recorder for MockMetricsRepository.
type MockMetricsRepositoryMockRecorder struct {
	mock *MockMetricsRepository
}

// NewMockMetricsRepository creates a new mock instance.
func NewMockMetricsRepository(ctrl *gomock.Controller) *MockMetricsRepository {
	mock := &MockMetricsRepository{ctrl: ctrl}
	mock.recorder = &MockMetricsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRepository) EXPECT() *MockMetricsRepositoryMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockMetricsRepository) CreateEvent(ctx context.Context, e *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockMetricsRepositoryMockRecorder) CreateEvent(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockMetricsRepository)(nil).CreateEvent), ctx, e)
}

// CreateMetric mocks base method.
func (m_2 *MockMetricsRepository) CreateMetric(ctx context.Context, m *models.Metric) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateMetric", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMetric indicates an expected call of CreateMetric.
func (mr *MockMetricsRepositoryMockRecorder) CreateMetric(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetric", reflect.TypeOf((*MockMetricsRepository)(nil).CreateMetric), ctx, m)
}

// FindEventByID mocks base method.
func (m *MockMetricsRepository) FindEventByID(ctx context.Context, id uuid.UUID) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEventByID", ctx, id)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEventByID indicates an expected call of FindEventByID.
func (mr *MockMetricsRepositoryMockRecorder) FindEventByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEventByID", reflect.TypeOf((*MockMetricsRepository)(nil).FindEventByID), ctx, id)
}

// ListEvents mocks base method.
func (m *MockMetricsRepository) ListEvents(ctx context.Context, filter models.EventFilterInput, from, to time.Time) ([]*models.Event, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, filter, from, to)
	ret0, _ := ret[0].([]*models.Event)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockMetricsRepositoryMockRecorder) ListEvents(ctx, filter, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockMetricsRepository)(nil).ListEvents), ctx, filter, from, to)
}

// ListMetrics mocks base method.
func (m *MockMetricsRepository) ListMetrics(ctx context.Context, filter models.MetricFilterInput, from, to time.Time) ([]*models.Metric, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetrics", ctx, filter, from, to)
	ret0, _ := ret[0].([]*models.Metric)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMetrics indicates an expected call of ListMetrics.
func (mr *MockMetricsRepositoryMockRecorder) ListMetrics(ctx, filter, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).ListMetrics), ctx, filter, from, to)
}
